export const MESSAGE_TYPES = {
  START_CAPTURE: "START_CAPTURE",
  STOP_CAPTURE: "STOP_CAPTURE",
  CLEANUP_ALL: "CLEANUP_ALL",
  SEND_COLOR: "SEND_COLOR",
  CLICKED: "CLICKED",
  SHOW_CAPTURE_MESSAGE: "SHOW_CAPTURE_MESSAGE",
};
